AppBayBackEnd/Models/Card.cs
namespace AppBayBackEnd.Models
{
    public class Card
    {
        public int Id { get; set; }
        public string CardTitle { get; set; }
        public string CardIcon { get; set; }
        public string CardDesc { get; set; }
    }
}

AppBayBackEnd/Models/Modern.cs
namespace AppBayBackEnd.Models
{
    public class Modern
    {
        public int Id { get; set; }
        public string ModernTitle { get; set; }
        public string ModernDesc { get; set; }
        public string ModernIcon { get; set; }

    }
}

AppBayBackEnd/Models/Slider.cs
namespace AppBayBackEnd.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string BackImageUrl { get; set; }
    }
}

AppBayBackEnd/ViewModels/HomeVM.cs
using AppBayBackEnd.Models;
using System.Collections.Generic;

namespace AppBayBackEnd.ViewModels
{
    public class HomeVM
    {
        public Slider sliders { get; set; }
        public IEnumerable<Card> cards { get; set; }
        public IEnumerable<Modern> modernCard { get; set; }

    }
}

AppBayBackEnd/Areas/Admin/Controllers/CardController.cs
using AppBayBackEnd.DAL;
using AppBayBackEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppBayBackEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CardController : Controller
    {
        
        private AppDbContext _context;
        public CardController(AppDbContext context)
        {
            _context=context;
        }
        public IActionResult Index()
        {
            List<Card> card = _context.Card.ToList();
            return View(card);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id==null)
                return NotFound();
            Card card =await _context.Card.FindAsync(id);
            if (card==null) return NotFound();
            return View(card);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id==null)
                return NotFound();
            Card card = await _context.Card.FindAsync(id);
            if (card==null) return NotFound();
            _context.Card.Remove(card);
           await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Card card)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            Card newCard = new Card();
            newCard.CardIcon = card.CardIcon;
            newCard.CardTitle = card.CardTitle;
            newCard.CardDesc = card.CardDesc;
            await _context.AddAsync(newCard);
            await _context.SaveChangesAsync();

                
            return View();
        }
    }
}

AppBayBackEnd/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppBayBackEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AppBayBackEnd/Controllers/HomeController.cs
using AppBayBackEnd.DAL;
using AppBayBackEnd.Models;
using AppBayBackEnd.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AppBayBackEnd.Controllers
{
    public class HomeController : Controller
    {
        private AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context=context;
        }
        public IActionResult Index()
        {
            HomeVM homeVM = new HomeVM();
            homeVM.sliders= _context.Slider.FirstOrDefault();
            homeVM.cards=_context.Card.ToList();
            homeVM.modernCard=_context.ModernCard.ToList();

            return View(homeVM);
        }
    }
}

AppBayBackEnd/Areas/Admin/Views/Card/Create.cshtml
@model Card
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
         <form class="forms-sample" method="post">
                    <div class="form-group">
                      <label asp-for="CardIcon">Icon</label>
                      <input  asp-for="CardIcon"  placeholder="Icon">
                      <sapan class="text-danger"  asp-validation-for="IconPath"></sapan>
                    </div>
                    <div class="form-group">
                      <label asp-for="CardTitle" >Title</label>
                      <input asp-for="CardTitle" placeholder="Title">
                      <sapan class="text-danger"  asp-validation-for="CardTitle"></sapan>

                    </div>
                    <div class="form-group">
                      <label asp-for="CardDesc">Description</label>
                      <input  asp-for="CardDesc" placeholder="Description">
                      <sapan class="text-danger"  asp-validation-for="Description"></sapan>

                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light" asp-controller="Card" asp-action="Index">Back</button>
                  </form>
    </div>
</div>

AppBayBackEnd/Areas/Admin/Views/Card/Detail.cshtml
@model Card
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/Admin/Views/shared/_AdminLayout.cshtml";
}

<h2>ID:@Model.Id</h2>
<h4>Desc:-@Model.CardDesc</h4>
<a class="btn btn-dark" asp-controller="Card" asp-action="Index">Back</a>

AppBayBackEnd/Areas/Admin/Views/Card/Index.cshtml
@model IEnumerable<Card>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/shared/_AdminLayout.cshtml";
    int count = 0;
}

         <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Card Table</h4>
                 <a class="btn btn-success" asp-action="Create" asp-controller="Card">Create</a>
                  <div class="table-responsive">
                    <table class="table">
                       
                            <thead>
                        <tr>
                          <th>Count</th>
                          <th>Icon</th>
                          <th>Title</th>
                          <th>Settings</th>
                        </tr>
                      </thead>
                      <tbody>
                           @foreach (var item in Model)
                        {
                            count++;
                        <tr>
                          <td>@count</td>
                          <td>@item.CardIcon</td>
                          <td>@item.CardTitle</td>
                          <td>
                              <a class="btn btn-info" asp-action="Update" asp-controller="Card"><i class="mdi mdi-credit-card"></i></a>
                              <a class="btn btn-danger" asp-action="Delete" asp-controller="Card" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i></a>
                              <a class="btn btn-info" asp-action="Detail" asp-controller="Card" asp-route-id="@item.Id"><i class="mdi mdi-information"></i></a>
                          </td>
                        </tr>
                        
                       }
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
           
          </div>

AppBayBackEnd/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Dashboard</h1>

AppBayBackEnd/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Majestic Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="~/admin/vendors/base/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="~/admin/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="~/admin/images/favicon.png" />
</head>
<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">  
          <a class="navbar-brand brand-logo" href="index.html"><img src="~/admin/images/logo.svg" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/admin/images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>  
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown mr-1">
            <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-message-text mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~.admin/images/faces/face4.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">David Grey
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    The meeting is cancelled
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~/admin/images/faces/face2.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">Tim Cook
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    New product launch
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~/admin/images/faces/face3.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal"> Johnson
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    Upcoming board meeting
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item dropdown mr-4">
            <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-bell mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-success">
                    <i class="mdi mdi-information mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-warning">
                    <i class="mdi mdi-settings mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-info">
                    <i class="mdi mdi-account-box mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="~/admin/images/faces/face5.jpg" alt="profile"/>
              <span class="nav-profile-name">Louis Barnett</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Settings
              </a>
              <a class="dropdown-item">
                <i class="mdi mdi-logout text-primary"></i>
                
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item asp-control">
            <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
      
          <li class="nav-item">
            <a class="nav-link" asp-controller="Card"  asp-action="Index">
              <i class="mdi mdi-view-headline menu-icon"></i>
              <span class="menu-title">Card</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/charts/chartjs.html">
              <i class="mdi mdi-chart-pie menu-icon"></i>
              <span class="menu-title">Charts</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/tables/basic-table.html">
              <i class="mdi mdi-grid-large menu-icon"></i>
              <span class="menu-title">Tables</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/icons/mdi.html">
              <i class="mdi mdi-emoticon menu-icon"></i>
              <span class="menu-title">Icons</span>
            </a>
          </li>
       
          <li class="nav-item">
            <a class="nav-link" href="documentation/documentation.html">
              <i class="mdi mdi-file-document-box-outline menu-icon"></i>
              <span class="menu-title">Documentation</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
        @RenderBody()
         </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="~/admin/vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="~/admin/vendors/chart.js/Chart.min.js"></script>
  <script src="~/admin/vendors/datatables.net/jquery.dataTables.js"></script>
  <script src="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="~/admin/js/off-canvas.js"></script>
  <script src="~/admin/js/hoverable-collapse.js"></script>
  <script src="~/admin/js/template.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="~/admin/js/dashboard.js"></script>
  <script src="~/admin/js/data-table.js"></script>
  <script src="~/admin/js/jquery.dataTables.js"></script>
  <script src="~/admin/js/dataTables.bootstrap4.js"></script>
  <!-- End custom js for this page-->
</body>

</html>

AppBayBackEnd/Views/Home/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Index";
}

<!-- Main start -->
    <main>
      <section id="intro-slider">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active slider-area">
                <img src="~/img/@Model.sliders.BackImageUrl" class="d-block w-100 slider-img" alt="...">
                <div class="mobile-screen">
                    
                </div>
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">

</div>
            </div>
            <div class="col-6 slider-mobile">
             <img src="~/img/@Model.sliders.ImageUrl" alt="">
            </div>
            <div class="col-6 slider-text ">
                <div class="download-app d-flex">
                    <!-- <div class="yanyanadush"></div>
                <div class="slider-icon">
                    <i class="fa-solid fa-mobile-screen-button download-icon"></i>
                </div> -->
                <!-- <div class="slider-content">

                    <div class="slider-title">
                        <span class="slider-title-main">Responsive App <br> <span class="app-desc">Landing Page</span> </span>
                    </div>
                  <div class="slider-desc">
                      <span class="slider-sub-title">Bootstrap Based Responsive Landing Page <br> Template.</span>
    
                  </div>
                </div> -->
                </div>
            </div>
         
            </div>
          </div>
      </section>
    </main>
    <!-- Main end -->

    <section id="page-cards">
        <div class="container">
            <div class="row">
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    @foreach (var item in Model.cards)
                    {
                    <div class="col">
                      <div class="card h-100 text-center">
                       @Html.Raw(item.CardIcon)
                        <div class="card-body">
                          <h5 class="card-title">@item.CardTitle</h5>
                          <p class="card-text">@item.CardDesc</p>
                        </div>
                       
                      </div>
                    </div>
                        
                    }
                       
            </div>
        </div>
    </section>
    <section id="modern ">
        
            <div class="container">
                <div class="row">
                    <div class="section-title text-center mt-5" >
                        <h3 class="modern-title">Modern & clean landing page theme</h3>
                        <p class="modern-subtitle">Lorem ipsum dolizzle sit tellivizzle, boom shackalack adipiscing elit. Nullam mofo velizzle, sure cool.</p>
                    </div>
                </div>
            <div class="modern-content d-flex   ">
                <div class="col-6 image-container">
                    <img src="~/img/tablet.png" alt="">
                </div>
                <div class="col-6 modern-context">
                    @foreach (var item in Model.modernCard)
                   {
                    <div class="card mb-3 modern-cards" style="max-width: 540px;">
                        <div class="row g-0">
                          <div class="col-1">
                            @Html.Raw(item.ModernIcon)
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="modern-card-title">@item.ModernTitle</h5>
                              <p class="card-text modern-text">@item.ModernDesc</p>
                             
                            </div>
                          </div>
                        </div>
                      </div>
                       
                   }
                     
                      
                </div>

            </div>
        </div>

    </section>
    <section id="footer-slider">
        <div class="container">
            <div class="row">
                <p class="text-center mt-5" style="color: #428BCA;font-size: 3rem; font-weight: 700;">What people say</p>
              <div id="slider">
                <ul>
                  <li>
                  <div class="slider-container">
                    <p>“Went with my wife, absolutely brilliant restaurant, the food tasted beautiful, so much depth and very well presented. As good if not better than any in the city centre. Will definitely be returning.” <br> Nathaniel Harwood – Google</p>
                  </div>
                  </li>
                  
                  
                    <li>
                    <div class="slider-container">
                    <p>“Great friendly service, the staff don't make you feel rushed, but are also very attentive, and on hand all the time if needed, best Thai food I have had in years, flavours are out of this world, and extremely good prices for the quality you get is top notch!!!!!! Love it” <br>David Armstrong - Porter – Google</p>
                  </div>
                  </li>
                    <li>
                    <div class="slider-container">
                    <p>“Possibly one of the best in Manchester. A menu designed and prepared by a very skilled chef, ably assisted by his wife who provides a friendly welcome. Always consistent and of high quality.” <br>Paul Fletcher – Google</p>
                  </div>
                  </li>
                    <li>
                    <div class="slider-container">
                    <p>“Food was amazing and service could not have been better...we went for a quick lunch as our office is opposite the restaurant...very quick service...I am highly recommending this restaurant to all my family and friends...” <br>Nic Gent – Facebook Page</p>
                  </div>
                  </li>
                   <li>
                    <div class="slider-container">
                    <p>“Went for the first time last night for my Husbands Birthday, friendly staff, very tasty food, would highly recommend, we will be back.” <br>Joanne Simms – Facebook Page</p>
                  </div>
                  </li>
                   <li>
                    <div class="slider-container">
                    <p>“A lovely, well decorated restaurant, where great food is served by very friendly staff for a bargain price. The food is authentic and delicious. We'll definitely be returning.”<br>Joe H – Trip Advisor</p>
                  </div>
                  </li>
                </ul>
                </div>
                   
                    
                    
            </div>
        </div>
    </section>

AppBayBackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"> 
    <link rel="stylesheet" href="~/css/style.css" />
    <title>AppBay</title>
  </head>
  <body>
    <section id="header-section">
    <!-- Header start -->
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid kkkk">
            <a class="navbar-brand" href="#">
              <i class="fa-solid fa-mobile-screen logo-icon"></i>
              <span class="app">App</span>
              <span class="bay">Bay</span>
            </a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>

            <div
              class="collapse navbar-collapse nav-main-list"
              id="navbarNavDropdown"
            >
              <ul class="navbar-nav nav-links">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#"
                    >Features</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">The App</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdownMenuLink"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Testimonial
                  </a>
                  <ul
                    class="dropdown-menu"
                    aria-labelledby="navbarDropdownMenuLink"
                  >
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li>
                      <a class="dropdown-item" href="#">Another action</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">Something else here</a>
                      </li>
                    
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </section>
    <!-- Header end -->
    <div>
        @RenderBody()
     </div>
        </body>
<footer>
    <div class="footer-basic">
    <p class="copyright">Company Name © 2022 AppBay All Rights Reserved | Built by Ahmed</p>
    <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
    </div>
  </footer>
 
  <script src="~/js/script.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"
  ></script>
  </html>